server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/foodmind
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=CHANGE_THIS_TO_A_LONG_SECRET_KEY_AT_LEAST_32_CHARSqweqeqeqweqweqwq
jwt.expiration=86400000

app.cors.allowed-origins=

spring.docker.compose.enabled=false