--
-- PostgreSQL database dump
--

\restrict aRIRKUakTCjpSQ9pH813D5cxbtnaCYuvagqCgd38IPNim3uoDvCnhL7fjky8cep

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS foodmind;
--
-- Name: foodmind; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE foodmind WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_Singapore.1252';


ALTER DATABASE foodmind OWNER TO postgres;

\unrestrict aRIRKUakTCjpSQ9pH813D5cxbtnaCYuvagqCgd38IPNim3uoDvCnhL7fjky8cep
\connect foodmind
\restrict aRIRKUakTCjpSQ9pH813D5cxbtnaCYuvagqCgd38IPNim3uoDvCnhL7fjky8cep

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_generation_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ai_generation_logs (
    id bigint NOT NULL,
    user_id bigint,
    purpose character varying(40) NOT NULL,
    provider character varying(60),
    request_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    response_json jsonb,
    status character varying(20) DEFAULT 'SUCCESS'::character varying NOT NULL,
    error_message character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_ai_generation_logs_purpose CHECK (((purpose)::text = ANY ((ARRAY['RECOMMENDATION_EXPLANATION'::character varying, 'WEEKLY_RECAP'::character varying, 'GROUP_DECISION'::character varying])::text[]))),
    CONSTRAINT chk_ai_generation_logs_status CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying, 'FALLBACK_USED'::character varying])::text[])))
);


ALTER TABLE public.ai_generation_logs OWNER TO postgres;

--
-- Name: ai_generation_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ai_generation_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_generation_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.badges (
    id bigint NOT NULL,
    code character varying(60) NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.badges OWNER TO postgres;

--
-- Name: badges_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: borrowed_recommendations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.borrowed_recommendations (
    id bigint NOT NULL,
    borrower_id bigint NOT NULL,
    source_user_id bigint NOT NULL,
    source_record_type character varying(20) NOT NULL,
    source_meal_record_id bigint,
    source_drink_record_id bigint,
    result_rating numeric(2,1),
    liked boolean,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_borrowed_recommendations_exactly_one_source CHECK (((((source_record_type)::text = 'MEAL'::text) AND (source_meal_record_id IS NOT NULL) AND (source_drink_record_id IS NULL)) OR (((source_record_type)::text = 'DRINK'::text) AND (source_drink_record_id IS NOT NULL) AND (source_meal_record_id IS NULL)))),
    CONSTRAINT chk_borrowed_recommendations_not_self CHECK ((borrower_id <> source_user_id)),
    CONSTRAINT chk_borrowed_recommendations_rating CHECK (((result_rating IS NULL) OR ((result_rating >= (0)::numeric) AND (result_rating <= (5)::numeric)))),
    CONSTRAINT chk_borrowed_recommendations_type CHECK (((source_record_type)::text = ANY ((ARRAY['MEAL'::character varying, 'DRINK'::character varying])::text[])))
);


ALTER TABLE public.borrowed_recommendations OWNER TO postgres;

--
-- Name: borrowed_recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.borrowed_recommendations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.borrowed_recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuisine_preferences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuisine_preferences (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    cuisine_name character varying(80) NOT NULL,
    preference_type character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_cuisine_preferences_type CHECK (((preference_type)::text = ANY ((ARRAY['LIKE'::character varying, 'DISLIKE'::character varying])::text[])))
);


ALTER TABLE public.cuisine_preferences OWNER TO postgres;

--
-- Name: cuisine_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuisine_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuisine_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dietary_restrictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dietary_restrictions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    restriction_name character varying(100) NOT NULL,
    severity character varying(20) DEFAULT 'NORMAL'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_dietary_restrictions_severity CHECK (((severity)::text = ANY ((ARRAY['LOW'::character varying, 'NORMAL'::character varying, 'STRICT'::character varying])::text[])))
);


ALTER TABLE public.dietary_restrictions OWNER TO postgres;

--
-- Name: dietary_restrictions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dietary_restrictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dietary_restrictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drink_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drink_records (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id bigint,
    shop_id bigint,
    drink_name character varying(160) NOT NULL,
    shop_name character varying(160),
    sweetness_level character varying(20),
    ice_level character varying(20),
    price numeric(10,2),
    rating numeric(2,1),
    comment character varying(255),
    photo_url character varying(255),
    would_buy_again boolean,
    privacy_level character varying(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
    consumed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_drink_records_group_privacy CHECK ((((privacy_level)::text <> 'GROUP'::text) OR (group_id IS NOT NULL))),
    CONSTRAINT chk_drink_records_ice CHECK (((ice_level IS NULL) OR ((ice_level)::text = ANY ((ARRAY['NO_ICE'::character varying, 'LESS_ICE'::character varying, 'NORMAL_ICE'::character varying, 'EXTRA_ICE'::character varying, 'HOT'::character varying])::text[])))),
    CONSTRAINT chk_drink_records_price CHECK (((price IS NULL) OR (price >= (0)::numeric))),
    CONSTRAINT chk_drink_records_privacy CHECK (((privacy_level)::text = ANY ((ARRAY['PRIVATE'::character varying, 'FRIENDS'::character varying, 'GROUP'::character varying, 'PUBLIC'::character varying])::text[]))),
    CONSTRAINT chk_drink_records_rating CHECK (((rating IS NULL) OR ((rating >= (0)::numeric) AND (rating <= (5)::numeric)))),
    CONSTRAINT chk_drink_records_sweetness CHECK (((sweetness_level IS NULL) OR ((sweetness_level)::text = ANY ((ARRAY['ZERO'::character varying, 'LESS'::character varying, 'HALF'::character varying, 'NORMAL'::character varying, 'EXTRA'::character varying])::text[]))))
);


ALTER TABLE public.drink_records OWNER TO postgres;

--
-- Name: drink_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.drink_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drink_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_groups (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    owner_id bigint NOT NULL,
    invite_code character varying(16) DEFAULT upper(substr(encode(public.gen_random_bytes(6), 'hex'::text), 1, 12)) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_food_groups_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ARCHIVED'::character varying, 'DELETED'::character varying])::text[])))
);


ALTER TABLE public.food_groups OWNER TO postgres;

--
-- Name: food_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_items (
    id bigint NOT NULL,
    restaurant_id bigint,
    name character varying(160) NOT NULL,
    cuisine_type character varying(80),
    category character varying(80),
    typical_price numeric(10,2),
    created_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_food_items_typical_price CHECK (((typical_price IS NULL) OR (typical_price >= (0)::numeric)))
);


ALTER TABLE public.food_items OWNER TO postgres;

--
-- Name: food_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.food_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friendships; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friendships (
    id bigint NOT NULL,
    requester_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_friendships_not_self CHECK ((requester_id <> receiver_id)),
    CONSTRAINT chk_friendships_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.friendships OWNER TO postgres;

--
-- Name: friendships_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.friendships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_members (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) DEFAULT 'MEMBER'::character varying NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    left_at timestamp with time zone,
    CONSTRAINT chk_group_members_role CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[]))),
    CONSTRAINT chk_group_members_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LEFT'::character varying, 'REMOVED'::character varying])::text[])))
);


ALTER TABLE public.group_members OWNER TO postgres;

--
-- Name: group_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meal_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meal_records (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id bigint,
    restaurant_id bigint,
    food_item_id bigint,
    food_name character varying(160) NOT NULL,
    restaurant_name character varying(160),
    cuisine_type character varying(80),
    meal_type character varying(20) NOT NULL,
    price numeric(10,2),
    rating numeric(2,1),
    comment character varying(255),
    photo_url character varying(255),
    would_eat_again boolean,
    privacy_level character varying(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
    consumed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_meal_records_group_privacy CHECK ((((privacy_level)::text <> 'GROUP'::text) OR (group_id IS NOT NULL))),
    CONSTRAINT chk_meal_records_meal_type CHECK (((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SUPPER'::character varying, 'SNACK'::character varying])::text[]))),
    CONSTRAINT chk_meal_records_price CHECK (((price IS NULL) OR (price >= (0)::numeric))),
    CONSTRAINT chk_meal_records_privacy CHECK (((privacy_level)::text = ANY ((ARRAY['PRIVATE'::character varying, 'FRIENDS'::character varying, 'GROUP'::character varying, 'PUBLIC'::character varying])::text[]))),
    CONSTRAINT chk_meal_records_rating CHECK (((rating IS NULL) OR ((rating >= (0)::numeric) AND (rating <= (5)::numeric))))
);


ALTER TABLE public.meal_records OWNER TO postgres;

--
-- Name: meal_records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meal_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meal_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recommendation_feedback (
    id bigint NOT NULL,
    recommendation_item_id bigint NOT NULL,
    user_id bigint NOT NULL,
    action character varying(30) NOT NULL,
    feedback_comment character varying(255),
    post_meal_rating numeric(2,1),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_recommendation_feedback_action CHECK (((action)::text = ANY ((ARRAY['SELECTED'::character varying, 'REJECTED'::character varying, 'ATE_LIKED'::character varying, 'ATE_DISLIKED'::character varying])::text[]))),
    CONSTRAINT chk_recommendation_feedback_rating CHECK (((post_meal_rating IS NULL) OR ((post_meal_rating >= (0)::numeric) AND (post_meal_rating <= (5)::numeric))))
);


ALTER TABLE public.recommendation_feedback OWNER TO postgres;

--
-- Name: recommendation_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recommendation_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recommendation_items (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    rank_position smallint NOT NULL,
    name character varying(160) NOT NULL,
    restaurant_name character varying(160),
    recommendation_type character varying(30) NOT NULL,
    source character varying(40) NOT NULL,
    score numeric(5,2) NOT NULL,
    reason character varying(255) NOT NULL,
    candidate_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    selected boolean DEFAULT false NOT NULL,
    rejected boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_recommendation_items_rank CHECK ((rank_position > 0)),
    CONSTRAINT chk_recommendation_items_score CHECK (((score >= (0)::numeric) AND (score <= (100)::numeric))),
    CONSTRAINT chk_recommendation_items_selected_rejected CHECK ((NOT ((selected = true) AND (rejected = true)))),
    CONSTRAINT chk_recommendation_items_source CHECK (((source)::text = ANY ((ARRAY['HISTORY'::character varying, 'PREFERENCE'::character varying, 'HISTORY_AND_PREFERENCE'::character varying, 'FRIEND_TRUST'::character varying, 'GROUP_POPULAR'::character varying, 'MANUAL_CATALOG'::character varying, 'AI_ASSISTED'::character varying])::text[]))),
    CONSTRAINT chk_recommendation_items_type CHECK (((recommendation_type)::text = ANY ((ARRAY['SAFE_OPTION'::character varying, 'EXPLORE_OPTION'::character varying, 'FRIEND_PICK'::character varying])::text[])))
);


ALTER TABLE public.recommendation_items OWNER TO postgres;

--
-- Name: recommendation_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recommendation_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recommendation_requests (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id bigint,
    meal_type character varying(20),
    budget_max numeric(10,2),
    mood character varying(40),
    location_area character varying(120),
    avoid_items text[],
    context_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_recommendation_requests_budget CHECK (((budget_max IS NULL) OR (budget_max >= (0)::numeric))),
    CONSTRAINT chk_recommendation_requests_meal_type CHECK (((meal_type IS NULL) OR ((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SUPPER'::character varying, 'SNACK'::character varying])::text[]))))
);


ALTER TABLE public.recommendation_requests OWNER TO postgres;

--
-- Name: recommendation_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recommendation_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.restaurants (
    id bigint NOT NULL,
    name character varying(160) NOT NULL,
    area character varying(120),
    address character varying(255),
    cuisine_type character varying(80),
    has_physical_store boolean,
    dine_in_available boolean,
    safety_note character varying(255),
    source_url character varying(255),
    created_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.restaurants OWNER TO postgres;

--
-- Name: restaurants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.restaurants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_badges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_badges (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    badge_id bigint NOT NULL,
    earned_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.user_badges OWNER TO postgres;

--
-- Name: user_badges_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    budget_min numeric(10,2),
    budget_max numeric(10,2),
    spicy_tolerance smallint DEFAULT 0 NOT NULL,
    location_area character varying(120),
    food_goal character varying(40),
    default_privacy_level character varying(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_user_profiles_budget CHECK ((((budget_min IS NULL) OR (budget_min >= (0)::numeric)) AND ((budget_max IS NULL) OR (budget_max >= (0)::numeric)) AND ((budget_min IS NULL) OR (budget_max IS NULL) OR (budget_min <= budget_max)))),
    CONSTRAINT chk_user_profiles_default_privacy CHECK (((default_privacy_level)::text = ANY ((ARRAY['PRIVATE'::character varying, 'FRIENDS'::character varying, 'GROUP'::character varying, 'PUBLIC'::character varying])::text[]))),
    CONSTRAINT chk_user_profiles_food_goal CHECK (((food_goal IS NULL) OR ((food_goal)::text = ANY ((ARRAY['AVOID_REPETITION'::character varying, 'SAVE_MONEY'::character varying, 'EAT_HEALTHIER'::character varying, 'DISCOVER_NEW_FOOD'::character varying, 'FOLLOW_FRIENDS'::character varying])::text[])))),
    CONSTRAINT chk_user_profiles_spicy CHECK (((spicy_tolerance >= 0) AND (spicy_tolerance <= 5)))
);


ALTER TABLE public.user_profiles OWNER TO postgres;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(80) NOT NULL,
    avatar_url character varying(255),
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_users_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v_group_feed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.v_group_feed (
    record_id bigint NOT NULL,
    record_type character varying(20) NOT NULL,
    comment character varying(255),
    consumed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    cuisine_type character varying(80),
    group_id bigint,
    item_name character varying(160),
    meal_type character varying(20),
    photo_url character varying(255),
    place_name character varying(160),
    price numeric(10,2),
    rating numeric(2,1),
    user_id bigint,
    username character varying(80),
    would_have_again boolean,
    CONSTRAINT v_group_feed_meal_type_check CHECK (((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SUPPER'::character varying, 'SNACK'::character varying])::text[]))),
    CONSTRAINT v_group_feed_record_type_check CHECK (((record_type)::text = ANY ((ARRAY['MEAL'::character varying, 'DRINK'::character varying])::text[])))
);


ALTER TABLE public.v_group_feed OWNER TO postgres;

--
-- Name: want_to_try_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.want_to_try_items (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    source_record_type character varying(20) NOT NULL,
    source_meal_record_id bigint,
    source_drink_record_id bigint,
    note character varying(255),
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_want_to_try_exactly_one_source CHECK (((((source_record_type)::text = 'MEAL'::text) AND (source_meal_record_id IS NOT NULL) AND (source_drink_record_id IS NULL)) OR (((source_record_type)::text = 'DRINK'::text) AND (source_drink_record_id IS NOT NULL) AND (source_meal_record_id IS NULL)))),
    CONSTRAINT chk_want_to_try_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'TRIED'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT chk_want_to_try_type CHECK (((source_record_type)::text = ANY ((ARRAY['MEAL'::character varying, 'DRINK'::character varying])::text[])))
);


ALTER TABLE public.want_to_try_items OWNER TO postgres;

--
-- Name: want_to_try_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.want_to_try_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.want_to_try_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weekly_recaps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.weekly_recaps (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    week_start date NOT NULL,
    week_end date NOT NULL,
    summary_text character varying(255),
    stats_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    ai_generated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_weekly_recaps_dates CHECK ((week_end >= week_start))
);


ALTER TABLE public.weekly_recaps OWNER TO postgres;

--
-- Name: weekly_recaps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.weekly_recaps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weekly_recaps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ai_generation_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ai_generation_logs (id, user_id, purpose, provider, request_json, response_json, status, error_message, created_at) FROM stdin;
\.


--
-- Data for Name: badges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.badges (id, code, name, description, created_at) FROM stdin;
1	FIRST_MEAL_LOGGED	First Meal Logged	Logged the first meal record.	2026-06-22 20:58:57.232814+08
2	SEVEN_DAY_FOOD_MEMORY	7-day Food Memory	Logged meals across seven days.	2026-06-22 20:58:57.232814+08
3	DRINK_EXPLORER	Drink Explorer	Logged several drink records.	2026-06-22 20:58:57.232814+08
4	NOT_REPEATING_TODAY	Not Repeating Today	Chose a meal that was not recently repeated.	2026-06-22 20:58:57.232814+08
5	FRIEND_PICK_TRIED	Friend Pick Tried	Tried a meal or drink inspired by a friend.	2026-06-22 20:58:57.232814+08
\.


--
-- Data for Name: borrowed_recommendations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.borrowed_recommendations (id, borrower_id, source_user_id, source_record_type, source_meal_record_id, source_drink_record_id, result_rating, liked, created_at) FROM stdin;
\.


--
-- Data for Name: cuisine_preferences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cuisine_preferences (id, user_id, cuisine_name, preference_type, created_at) FROM stdin;
\.


--
-- Data for Name: dietary_restrictions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dietary_restrictions (id, user_id, restriction_name, severity, created_at) FROM stdin;
\.


--
-- Data for Name: drink_records; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drink_records (id, user_id, group_id, shop_id, drink_name, shop_name, sweetness_level, ice_level, price, rating, comment, photo_url, would_buy_again, privacy_level, consumed_at, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: food_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_groups (id, name, description, owner_id, invite_code, status, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: food_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.food_items (id, restaurant_id, name, cuisine_type, category, typical_price, created_by, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: friendships; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.friendships (id, requester_id, receiver_id, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: group_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.group_members (id, group_id, user_id, role, status, joined_at, left_at) FROM stdin;
\.


--
-- Data for Name: meal_records; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meal_records (id, user_id, group_id, restaurant_id, food_item_id, food_name, restaurant_name, cuisine_type, meal_type, price, rating, comment, photo_url, would_eat_again, privacy_level, consumed_at, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: recommendation_feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recommendation_feedback (id, recommendation_item_id, user_id, action, feedback_comment, post_meal_rating, created_at) FROM stdin;
\.


--
-- Data for Name: recommendation_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recommendation_items (id, request_id, rank_position, name, restaurant_name, recommendation_type, source, score, reason, candidate_json, selected, rejected, created_at) FROM stdin;
\.


--
-- Data for Name: recommendation_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recommendation_requests (id, user_id, group_id, meal_type, budget_max, mood, location_area, avoid_items, context_json, created_at) FROM stdin;
\.


--
-- Data for Name: restaurants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.restaurants (id, name, area, address, cuisine_type, has_physical_store, dine_in_available, safety_note, source_url, created_by, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: user_badges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_badges (id, user_id, badge_id, earned_at) FROM stdin;
\.


--
-- Data for Name: user_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_profiles (id, user_id, budget_min, budget_max, spicy_tolerance, location_area, food_goal, default_privacy_level, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password_hash, username, avatar_url, status, email_verified, last_login_at, created_at, updated_at, deleted_at) FROM stdin;
\.


--
-- Data for Name: v_group_feed; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.v_group_feed (record_id, record_type, comment, consumed_at, created_at, cuisine_type, group_id, item_name, meal_type, photo_url, place_name, price, rating, user_id, username, would_have_again) FROM stdin;
\.


--
-- Data for Name: want_to_try_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.want_to_try_items (id, user_id, source_record_type, source_meal_record_id, source_drink_record_id, note, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: weekly_recaps; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.weekly_recaps (id, user_id, week_start, week_end, summary_text, stats_json, ai_generated, created_at, updated_at) FROM stdin;
\.


--
-- Name: ai_generation_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ai_generation_logs_id_seq', 1, false);


--
-- Name: badges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.badges_id_seq', 5, true);


--
-- Name: borrowed_recommendations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.borrowed_recommendations_id_seq', 1, false);


--
-- Name: cuisine_preferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cuisine_preferences_id_seq', 1, false);


--
-- Name: dietary_restrictions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dietary_restrictions_id_seq', 1, false);


--
-- Name: drink_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.drink_records_id_seq', 1, false);


--
-- Name: food_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_groups_id_seq', 1, false);


--
-- Name: food_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.food_items_id_seq', 1, false);


--
-- Name: friendships_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.friendships_id_seq', 1, false);


--
-- Name: group_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.group_members_id_seq', 1, false);


--
-- Name: meal_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meal_records_id_seq', 1, false);


--
-- Name: recommendation_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recommendation_feedback_id_seq', 1, false);


--
-- Name: recommendation_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recommendation_items_id_seq', 1, false);


--
-- Name: recommendation_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recommendation_requests_id_seq', 1, false);


--
-- Name: restaurants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.restaurants_id_seq', 1, false);


--
-- Name: user_badges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_badges_id_seq', 1, false);


--
-- Name: user_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_profiles_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: want_to_try_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.want_to_try_items_id_seq', 1, false);


--
-- Name: weekly_recaps_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.weekly_recaps_id_seq', 1, false);


--
-- Name: ai_generation_logs ai_generation_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_generation_logs
    ADD CONSTRAINT ai_generation_logs_pkey PRIMARY KEY (id);


--
-- Name: badges badges_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_code_key UNIQUE (code);


--
-- Name: badges badges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY (id);


--
-- Name: borrowed_recommendations borrowed_recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_recommendations
    ADD CONSTRAINT borrowed_recommendations_pkey PRIMARY KEY (id);


--
-- Name: cuisine_preferences cuisine_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuisine_preferences
    ADD CONSTRAINT cuisine_preferences_pkey PRIMARY KEY (id);


--
-- Name: dietary_restrictions dietary_restrictions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dietary_restrictions
    ADD CONSTRAINT dietary_restrictions_pkey PRIMARY KEY (id);


--
-- Name: drink_records drink_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_records
    ADD CONSTRAINT drink_records_pkey PRIMARY KEY (id);


--
-- Name: food_groups food_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_groups
    ADD CONSTRAINT food_groups_pkey PRIMARY KEY (id);


--
-- Name: food_items food_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_items
    ADD CONSTRAINT food_items_pkey PRIMARY KEY (id);


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);


--
-- Name: meal_records meal_records_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT meal_records_pkey PRIMARY KEY (id);


--
-- Name: recommendation_feedback recommendation_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT recommendation_feedback_pkey PRIMARY KEY (id);


--
-- Name: recommendation_items recommendation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_items
    ADD CONSTRAINT recommendation_items_pkey PRIMARY KEY (id);


--
-- Name: recommendation_requests recommendation_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_requests
    ADD CONSTRAINT recommendation_requests_pkey PRIMARY KEY (id);


--
-- Name: restaurants restaurants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);


--
-- Name: user_badges user_badges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT user_badges_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: v_group_feed v_group_feed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.v_group_feed
    ADD CONSTRAINT v_group_feed_pkey PRIMARY KEY (record_id, record_type);


--
-- Name: want_to_try_items want_to_try_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.want_to_try_items
    ADD CONSTRAINT want_to_try_items_pkey PRIMARY KEY (id);


--
-- Name: weekly_recaps weekly_recaps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weekly_recaps
    ADD CONSTRAINT weekly_recaps_pkey PRIMARY KEY (id);


--
-- Name: idx_ai_generation_logs_request_json; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ai_generation_logs_request_json ON public.ai_generation_logs USING gin (request_json);


--
-- Name: idx_ai_generation_logs_user_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ai_generation_logs_user_created ON public.ai_generation_logs USING btree (user_id, created_at DESC);


--
-- Name: idx_borrowed_recommendations_borrower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_borrowed_recommendations_borrower ON public.borrowed_recommendations USING btree (borrower_id, created_at DESC);


--
-- Name: idx_borrowed_recommendations_source_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_borrowed_recommendations_source_user ON public.borrowed_recommendations USING btree (source_user_id, created_at DESC);


--
-- Name: idx_cuisine_preferences_user_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cuisine_preferences_user_type ON public.cuisine_preferences USING btree (user_id, preference_type);


--
-- Name: idx_drink_records_drink_name_lower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drink_records_drink_name_lower ON public.drink_records USING btree (lower((drink_name)::text));


--
-- Name: idx_drink_records_group_feed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drink_records_group_feed ON public.drink_records USING btree (group_id, consumed_at DESC) WHERE ((deleted_at IS NULL) AND ((privacy_level)::text = 'GROUP'::text));


--
-- Name: idx_drink_records_user_consumed_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drink_records_user_consumed_at ON public.drink_records USING btree (user_id, consumed_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_food_groups_owner; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_food_groups_owner ON public.food_groups USING btree (owner_id);


--
-- Name: idx_food_items_cuisine; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_food_items_cuisine ON public.food_items USING btree (cuisine_type);


--
-- Name: idx_food_items_name_lower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_food_items_name_lower ON public.food_items USING btree (lower((name)::text));


--
-- Name: idx_food_items_restaurant; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_food_items_restaurant ON public.food_items USING btree (restaurant_id);


--
-- Name: idx_friendships_receiver_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friendships_receiver_status ON public.friendships USING btree (receiver_id, status);


--
-- Name: idx_friendships_requester_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friendships_requester_status ON public.friendships USING btree (requester_id, status);


--
-- Name: idx_group_members_group_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_group_members_group_status ON public.group_members USING btree (group_id, status);


--
-- Name: idx_group_members_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_group_members_user_status ON public.group_members USING btree (user_id, status);


--
-- Name: idx_meal_records_cuisine; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_records_cuisine ON public.meal_records USING btree (cuisine_type);


--
-- Name: idx_meal_records_food_name_lower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_records_food_name_lower ON public.meal_records USING btree (lower((food_name)::text));


--
-- Name: idx_meal_records_group_feed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_records_group_feed ON public.meal_records USING btree (group_id, consumed_at DESC) WHERE ((deleted_at IS NULL) AND ((privacy_level)::text = 'GROUP'::text));


--
-- Name: idx_meal_records_meal_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_records_meal_type ON public.meal_records USING btree (meal_type);


--
-- Name: idx_meal_records_user_consumed_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meal_records_user_consumed_at ON public.meal_records USING btree (user_id, consumed_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_recommendation_feedback_user_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recommendation_feedback_user_created ON public.recommendation_feedback USING btree (user_id, created_at DESC);


--
-- Name: idx_recommendation_items_candidate_json; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recommendation_items_candidate_json ON public.recommendation_items USING gin (candidate_json);


--
-- Name: idx_recommendation_items_request_score; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recommendation_items_request_score ON public.recommendation_items USING btree (request_id, score DESC);


--
-- Name: idx_recommendation_requests_context_json; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recommendation_requests_context_json ON public.recommendation_requests USING gin (context_json);


--
-- Name: idx_recommendation_requests_user_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recommendation_requests_user_created ON public.recommendation_requests USING btree (user_id, created_at DESC);


--
-- Name: idx_restaurants_area; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_restaurants_area ON public.restaurants USING btree (area);


--
-- Name: idx_restaurants_cuisine; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_restaurants_cuisine ON public.restaurants USING btree (cuisine_type);


--
-- Name: idx_restaurants_name_lower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_restaurants_name_lower ON public.restaurants USING btree (lower((name)::text));


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: idx_want_to_try_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_want_to_try_user_status ON public.want_to_try_items USING btree (user_id, status);


--
-- Name: idx_weekly_recaps_stats_json; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_weekly_recaps_stats_json ON public.weekly_recaps USING gin (stats_json);


--
-- Name: ux_cuisine_preferences_user_cuisine; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_cuisine_preferences_user_cuisine ON public.cuisine_preferences USING btree (user_id, lower((cuisine_name)::text));


--
-- Name: ux_dietary_restrictions_user_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_dietary_restrictions_user_name ON public.dietary_restrictions USING btree (user_id, lower((restriction_name)::text));


--
-- Name: ux_food_groups_invite_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_food_groups_invite_code ON public.food_groups USING btree (invite_code);


--
-- Name: ux_friendships_pair; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_friendships_pair ON public.friendships USING btree (LEAST(requester_id, receiver_id), GREATEST(requester_id, receiver_id));


--
-- Name: ux_group_members_group_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_group_members_group_user ON public.group_members USING btree (group_id, user_id);


--
-- Name: ux_recommendation_items_request_rank; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_recommendation_items_request_rank ON public.recommendation_items USING btree (request_id, rank_position);


--
-- Name: ux_user_badges_user_badge; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_user_badges_user_badge ON public.user_badges USING btree (user_id, badge_id);


--
-- Name: ux_users_email_lower; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_users_email_lower ON public.users USING btree (lower((email)::text));


--
-- Name: ux_weekly_recaps_user_week; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_weekly_recaps_user_week ON public.weekly_recaps USING btree (user_id, week_start);


--
-- Name: drink_records trg_drink_records_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_drink_records_updated_at BEFORE UPDATE ON public.drink_records FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: food_groups trg_food_groups_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_food_groups_updated_at BEFORE UPDATE ON public.food_groups FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: food_items trg_food_items_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_food_items_updated_at BEFORE UPDATE ON public.food_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: friendships trg_friendships_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_friendships_updated_at BEFORE UPDATE ON public.friendships FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: meal_records trg_meal_records_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_meal_records_updated_at BEFORE UPDATE ON public.meal_records FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: restaurants trg_restaurants_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_restaurants_updated_at BEFORE UPDATE ON public.restaurants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: user_profiles trg_user_profiles_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_user_profiles_updated_at BEFORE UPDATE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: users trg_users_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: want_to_try_items trg_want_to_try_items_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_want_to_try_items_updated_at BEFORE UPDATE ON public.want_to_try_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: weekly_recaps trg_weekly_recaps_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_weekly_recaps_updated_at BEFORE UPDATE ON public.weekly_recaps FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ai_generation_logs fk_ai_generation_logs_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ai_generation_logs
    ADD CONSTRAINT fk_ai_generation_logs_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: borrowed_recommendations fk_borrowed_recommendations_borrower; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_recommendations
    ADD CONSTRAINT fk_borrowed_recommendations_borrower FOREIGN KEY (borrower_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: borrowed_recommendations fk_borrowed_recommendations_drink; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_recommendations
    ADD CONSTRAINT fk_borrowed_recommendations_drink FOREIGN KEY (source_drink_record_id) REFERENCES public.drink_records(id) ON DELETE CASCADE;


--
-- Name: borrowed_recommendations fk_borrowed_recommendations_meal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_recommendations
    ADD CONSTRAINT fk_borrowed_recommendations_meal FOREIGN KEY (source_meal_record_id) REFERENCES public.meal_records(id) ON DELETE CASCADE;


--
-- Name: borrowed_recommendations fk_borrowed_recommendations_source_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_recommendations
    ADD CONSTRAINT fk_borrowed_recommendations_source_user FOREIGN KEY (source_user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: cuisine_preferences fk_cuisine_preferences_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuisine_preferences
    ADD CONSTRAINT fk_cuisine_preferences_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: dietary_restrictions fk_dietary_restrictions_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dietary_restrictions
    ADD CONSTRAINT fk_dietary_restrictions_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: drink_records fk_drink_records_group; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_records
    ADD CONSTRAINT fk_drink_records_group FOREIGN KEY (group_id) REFERENCES public.food_groups(id) ON DELETE SET NULL;


--
-- Name: drink_records fk_drink_records_shop; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_records
    ADD CONSTRAINT fk_drink_records_shop FOREIGN KEY (shop_id) REFERENCES public.restaurants(id) ON DELETE SET NULL;


--
-- Name: drink_records fk_drink_records_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_records
    ADD CONSTRAINT fk_drink_records_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: food_groups fk_food_groups_owner; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_groups
    ADD CONSTRAINT fk_food_groups_owner FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: food_items fk_food_items_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_items
    ADD CONSTRAINT fk_food_items_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: food_items fk_food_items_restaurant; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_items
    ADD CONSTRAINT fk_food_items_restaurant FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id) ON DELETE SET NULL;


--
-- Name: friendships fk_friendships_receiver; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fk_friendships_receiver FOREIGN KEY (receiver_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: friendships fk_friendships_requester; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: group_members fk_group_members_group; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES public.food_groups(id) ON DELETE CASCADE;


--
-- Name: group_members fk_group_members_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: meal_records fk_meal_records_food_item; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT fk_meal_records_food_item FOREIGN KEY (food_item_id) REFERENCES public.food_items(id) ON DELETE SET NULL;


--
-- Name: meal_records fk_meal_records_group; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT fk_meal_records_group FOREIGN KEY (group_id) REFERENCES public.food_groups(id) ON DELETE SET NULL;


--
-- Name: meal_records fk_meal_records_restaurant; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT fk_meal_records_restaurant FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id) ON DELETE SET NULL;


--
-- Name: meal_records fk_meal_records_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meal_records
    ADD CONSTRAINT fk_meal_records_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: recommendation_feedback fk_recommendation_feedback_item; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT fk_recommendation_feedback_item FOREIGN KEY (recommendation_item_id) REFERENCES public.recommendation_items(id) ON DELETE CASCADE;


--
-- Name: recommendation_feedback fk_recommendation_feedback_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_feedback
    ADD CONSTRAINT fk_recommendation_feedback_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: recommendation_items fk_recommendation_items_request; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_items
    ADD CONSTRAINT fk_recommendation_items_request FOREIGN KEY (request_id) REFERENCES public.recommendation_requests(id) ON DELETE CASCADE;


--
-- Name: recommendation_requests fk_recommendation_requests_group; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_requests
    ADD CONSTRAINT fk_recommendation_requests_group FOREIGN KEY (group_id) REFERENCES public.food_groups(id) ON DELETE SET NULL;


--
-- Name: recommendation_requests fk_recommendation_requests_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation_requests
    ADD CONSTRAINT fk_recommendation_requests_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: restaurants fk_restaurants_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT fk_restaurants_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: user_badges fk_user_badges_badge; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES public.badges(id) ON DELETE CASCADE;


--
-- Name: user_badges fk_user_badges_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fk_user_badges_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_profiles fk_user_profiles_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: want_to_try_items fk_want_to_try_drink; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.want_to_try_items
    ADD CONSTRAINT fk_want_to_try_drink FOREIGN KEY (source_drink_record_id) REFERENCES public.drink_records(id) ON DELETE CASCADE;


--
-- Name: want_to_try_items fk_want_to_try_meal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.want_to_try_items
    ADD CONSTRAINT fk_want_to_try_meal FOREIGN KEY (source_meal_record_id) REFERENCES public.meal_records(id) ON DELETE CASCADE;


--
-- Name: want_to_try_items fk_want_to_try_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.want_to_try_items
    ADD CONSTRAINT fk_want_to_try_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: weekly_recaps fk_weekly_recaps_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weekly_recaps
    ADD CONSTRAINT fk_weekly_recaps_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict aRIRKUakTCjpSQ9pH813D5cxbtnaCYuvagqCgd38IPNim3uoDvCnhL7fjky8cep

